imbunatatire UI + obtiunea de search
Turing99/notes-app pull request #4
Opened 2021-10-24 11:38 UTC by Turing99

-am reusit sa modific stilul si sa nu mai am problemele de afisare cu select box-ul;
-am legat componentele(cea de filtrare si home) intre ele folosind adnotarile de @Input si @Output;
-crearea unui input ce cauta o notita in functie de nume sau descriere;

2021-10-26 18:56 UTC, gaborvlad13 requested changes
Pease update the pull request deleting the blank lines, formatting the code and naming the variables using camel case.

2021-10-31 10:15 UTC, Turing99 reviewed
Modificarile aduse in acest commit au fost:
-crearea unei directive custom ce are rolul de a modifica culoarea textului in functie de ce radio button a fost selectat;
-formatarea codului prin modicicarea unor variabile in camelCase;
-mockuirea backendului;

2021-10-31 15:42 UTC, gaborvlad13 approved these changes

2021-10-31 15:42 UTC, gaborvlad13 commented on src/app/add-note/add-note.component.ts
> +    private filter_categories: FilterCategoriesServices,
```suggestion
    private filterCategories: FilterCategoriesServices,
```

2021-10-31 15:42 UTC, gaborvlad13 commented on src/app/add-note/add-note.component.ts
> +    private _activatedRoute: ActivatedRoute,
```suggestion
    private activatedRoute: ActivatedRoute,
```

2021-10-31 15:42 UTC, gaborvlad13 commented on src/app/note/note.component.html
> +            aria-label="Example icon button with a subdirectory_arrow_right icon"
Can you use a more suggestive aria-label? Same for below

2021-10-31 15:47 UTC, gaborvlad13 commented
Please wait until our tomorrow's meeting to merge  this pull request

2021-11-04 19:00 UTC, merged